/* ==================== SYLLABUS STRUCTURE ==================== */
const SYLLABUS = [
  { code:'M1-R5', title:'IT Tools and Network Basics', color:'#64FFDA',
    desc:'Computer fundamentals, OS basics, word processing, spreadsheets, presentations, networking & cyber security.',
    topics:[
      {title:'Introduction to Computers', sub:['Computer organisation','I/O devices','Memory & storage','Number systems']},
      {title:'Operating System Basics', sub:['Windows/Linux basics','File management','Utility software']},
      {title:'Word Processing', sub:['Formatting','Mail merge','Tables']},
      {title:'Spreadsheets', sub:['Formulas & functions','Charts','Sorting/filtering']},
      {title:'Presentations', sub:['Slide design','Animations','Slide master']},
      {title:'Networking Concepts', sub:['Network types','Topologies','Internet basics','Cyber security']},
    ]},
  { code:'M2-R5', title:'Web Designing & Publishing', color:'#9D7BFF',
    desc:'HTML5, CSS3, JavaScript basics, responsive design and website publishing workflow.',
    topics:[
      {title:'HTML5 Fundamentals', sub:['Tags & elements','Forms','Tables','Semantic HTML']},
      {title:'CSS3 Styling', sub:['Selectors','Box model','Flexbox & Grid','Responsive design']},
      {title:'JavaScript Basics', sub:['Variables','Functions','DOM manipulation','Events']},
      {title:'Website Publishing', sub:['Domain & hosting','FTP basics','SEO fundamentals']},
    ]},
  { code:'M3-R5', title:'Programming through Python', color:'#FFC46B',
    desc:'Python syntax, control structures, functions, data structures, file handling and OOP basics.',
    topics:[
      {title:'Python Basics', sub:['Variables','Data types','Operators','I/O']},
      {title:'Control Structures', sub:['if-elif-else','loops','break/continue']},
      {title:'Functions & Modules', sub:['Defining functions','Arguments','Built-in modules']},
      {title:'Data Structures', sub:['Lists','Tuples','Dictionaries','Sets']},
      {title:'File Handling', sub:['Read/write files','Exception handling']},
      {title:'OOP', sub:['Classes & objects','Inheritance','Encapsulation']},
    ]},
  { code:'M4-R5', title:'Internet of Things & Applications', color:'#4ADE80',
    desc:'IoT architecture, sensors & actuators, communication protocols, and real-world applications.',
    topics:[
      {title:'Introduction to IoT', sub:['Architecture','Characteristics','Applications']},
      {title:'Sensors & Actuators', sub:['Types of sensors','Microcontrollers']},
      {title:'Communication Protocols', sub:['MQTT','HTTP','Zigbee','Bluetooth/WiFi']},
      {title:'IoT Applications', sub:['Smart home','Smart agriculture','Industrial IoT','Security']},
    ]},
];

/* ==================== QUESTION BANK ==================== */
const QUESTIONS = [
// ---------- M1-R5 ----------
{id:'m1_1',module:'M1-R5',topic:'Introduction to Computers',diff:'easy',text:'Which number system is used internally by a computer to store data?',options:['Decimal','Binary','Octal','Hexadecimal'],correct:1,exp:'Computers store and process everything using binary (0s and 1s) because circuits have two stable states.'},
{id:'m1_2',module:'M1-R5',topic:'Introduction to Computers',diff:'medium',text:'Which of these is an example of secondary storage?',options:['RAM','Cache','Hard Disk','Register'],correct:2,exp:'Hard disks retain data even after power off, making them secondary (non-volatile) storage.'},
{id:'m1_3',module:'M1-R5',topic:'Introduction to Computers',diff:'easy',text:'Which device converts human-readable input into machine-readable form?',options:['Monitor','Keyboard','Printer','Speaker'],correct:1,exp:'Keyboard is an input device.'},
{id:'m1_4',module:'M1-R5',topic:'Introduction to Computers',diff:'medium',text:'1 Byte is equal to how many bits?',options:['4','8','16','32'],correct:1},
{id:'m1_5',module:'M1-R5',topic:'Operating System Basics',diff:'easy',text:'Which of these is an open-source operating system?',options:['Windows','Linux','macOS','iOS'],correct:1},
{id:'m1_6',module:'M1-R5',topic:'Operating System Basics',diff:'medium',text:'What is the primary function of an Operating System?',options:['Compile programs','Manage hardware and software resources','Design web pages','Create spreadsheets'],correct:1},
{id:'m1_7',module:'M1-R5',topic:'Operating System Basics',diff:'easy',text:'Which shortcut is commonly used to copy a file in Windows?',options:['Ctrl+X','Ctrl+C','Ctrl+V','Ctrl+Z'],correct:1},
{id:'m1_8',module:'M1-R5',topic:'Word Processing',diff:'easy',text:'Which feature is used to send the same letter to multiple recipients with different names/addresses?',options:['Mail Merge','Track Changes','Auto Correct','Word Count'],correct:0},
{id:'m1_9',module:'M1-R5',topic:'Word Processing',diff:'medium',text:'Which shortcut is used to make selected text Bold?',options:['Ctrl+B','Ctrl+I','Ctrl+U','Ctrl+D'],correct:0},
{id:'m1_10',module:'M1-R5',topic:'Word Processing',diff:'medium',text:'What is the default file extension for a LibreOffice Writer document?',options:['.docx','.odt','.txt','.rtf'],correct:1},
{id:'m1_11',module:'M1-R5',topic:'Spreadsheets',diff:'easy',text:'Which function returns the average of a range of cells?',options:['=SUM()','=AVERAGE()','=COUNT()','=MEDIAN()'],correct:1},
{id:'m1_12',module:'M1-R5',topic:'Spreadsheets',diff:'medium',text:'Which symbol must every formula in a spreadsheet begin with?',options:['@','#','=','$'],correct:2},
{id:'m1_13',module:'M1-R5',topic:'Spreadsheets',diff:'medium',text:'What does the function =COUNTIF() do?',options:['Adds numbers meeting a condition','Counts cells meeting a condition','Finds average','Sorts data'],correct:1},
{id:'m1_14',module:'M1-R5',topic:'Presentations',diff:'easy',text:'Which view in Impress is used to rearrange slide order easily?',options:['Slide Sorter','Normal View','Outline View','Notes View'],correct:0},
{id:'m1_15',module:'M1-R5',topic:'Presentations',diff:'medium',text:'What is a "Slide Master" used for?',options:['Adding animations only','Defining consistent formatting across all slides','Recording audio','Printing handouts'],correct:1},
{id:'m1_16',module:'M1-R5',topic:'Networking Concepts',diff:'easy',text:'Which network topology connects all devices to a single central hub?',options:['Bus','Ring','Star','Mesh'],correct:2},
{id:'m1_17',module:'M1-R5',topic:'Networking Concepts',diff:'medium',text:'What does "IP" stand for in IP Address?',options:['Internet Protocol','Internal Process','Internet Provider','Information Packet'],correct:0},
{id:'m1_18',module:'M1-R5',topic:'Networking Concepts',diff:'medium',text:'Which of these is a strong password practice?',options:['Using your name and birth year','Using the same password everywhere','Mixing upper/lowercase, numbers and symbols','Sharing password with friends'],correct:2},
{id:'m1_19',module:'M1-R5',topic:'Networking Concepts',diff:'hard',text:'A network confined to a single building or campus is called a:',options:['WAN','LAN','MAN','PAN'],correct:1},

// ---------- M2-R5 ----------
{id:'m2_1',module:'M2-R5',topic:'HTML5 Fundamentals',diff:'easy',text:'Which HTML5 tag is used to define navigation links?',options:['<section>','<nav>','<aside>','<header>'],correct:1},
{id:'m2_2',module:'M2-R5',topic:'HTML5 Fundamentals',diff:'easy',text:'Which tag is used to create a hyperlink?',options:['<link>','<a>','<href>','<url>'],correct:1},
{id:'m2_3',module:'M2-R5',topic:'HTML5 Fundamentals',diff:'medium',text:'Which attribute specifies an alternate text for an image if it fails to load?',options:['title','alt','src','longdesc'],correct:1},
{id:'m2_4',module:'M2-R5',topic:'HTML5 Fundamentals',diff:'medium',text:'Which input type is used for an email field in an HTML form?',options:['type="text"','type="mail"','type="email"','type="address"'],correct:2},
{id:'m2_5',module:'M2-R5',topic:'CSS3 Styling',diff:'easy',text:'Which CSS property creates space between flex items?',options:['margin','gap','padding','align-items'],correct:1},
{id:'m2_6',module:'M2-R5',topic:'CSS3 Styling',diff:'medium',text:'Which CSS property is used to change text color?',options:['font-color','text-color','color','background-color'],correct:2},
{id:'m2_7',module:'M2-R5',topic:'CSS3 Styling',diff:'medium',text:'In the CSS box model, which is the outermost layer?',options:['Content','Padding','Border','Margin'],correct:3},
{id:'m2_8',module:'M2-R5',topic:'CSS3 Styling',diff:'hard',text:'Which CSS unit is relative to the root element font size?',options:['em','px','rem','vh'],correct:2},
{id:'m2_9',module:'M2-R5',topic:'JavaScript Basics',diff:'easy',text:'Which method adds an element to the end of an array?',options:['push()','pop()','shift()','slice()'],correct:0},
{id:'m2_10',module:'M2-R5',topic:'JavaScript Basics',diff:'medium',text:'Which keyword declares a block-scoped variable in JavaScript?',options:['var','let','global','static'],correct:1},
{id:'m2_11',module:'M2-R5',topic:'JavaScript Basics',diff:'medium',text:'Which method is used to select an HTML element by its id in JavaScript?',options:['getElementById()','querySelectorId()','selectId()','findElement()'],correct:0},
{id:'m2_12',module:'M2-R5',topic:'JavaScript Basics',diff:'hard',text:'What does the "===" operator check in JavaScript?',options:['Only value equality','Only type equality','Both value and type equality','Neither'],correct:2},
{id:'m2_13',module:'M2-R5',topic:'Website Publishing',diff:'easy',text:'What does SEO stand for?',options:['Site Encryption Option','Search Engine Optimization','Server Extension Object','Secure Endpoint Operation'],correct:1},
{id:'m2_14',module:'M2-R5',topic:'Website Publishing',diff:'medium',text:'Which protocol is commonly used to upload files to a web server?',options:['HTTP','FTP','SMTP','POP3'],correct:1},

// ---------- M3-R5 ----------
{id:'m3_1',module:'M3-R5',topic:'Python Basics',diff:'easy',text:'Which of these is a mutable data type in Python?',options:['tuple','string','list','int'],correct:2},
{id:'m3_2',module:'M3-R5',topic:'Python Basics',diff:'easy',text:'Which function is used to display output in Python?',options:['print()','echo()','display()','show()'],correct:0},
{id:'m3_3',module:'M3-R5',topic:'Python Basics',diff:'medium',text:'What is the data type of the value `3.14` in Python?',options:['int','float','str','bool'],correct:1},
{id:'m3_4',module:'M3-R5',topic:'Python Basics',diff:'medium',text:'Which operator is used for exponentiation in Python?',options:['^','**','exp()','%%'],correct:1},
{id:'m3_5',module:'M3-R5',topic:'Control Structures',diff:'easy',text:'Which keyword exits a loop immediately?',options:['continue','break','pass','return'],correct:1},
{id:'m3_6',module:'M3-R5',topic:'Control Structures',diff:'medium',text:'Which keyword skips the current iteration and continues with the next?',options:['break','continue','pass','stop'],correct:1},
{id:'m3_7',module:'M3-R5',topic:'Control Structures',diff:'medium',text:'Which loop is guaranteed to run at least once in general programming logic?',options:['for','while','do-while','if'],correct:2,exp:'Python does not have a native do-while, but conceptually it runs the body before checking the condition.'},
{id:'m3_8',module:'M3-R5',topic:'Functions & Modules',diff:'easy',text:'Which keyword is used to define a function in Python?',options:['function','def','func','define'],correct:1},
{id:'m3_9',module:'M3-R5',topic:'Functions & Modules',diff:'medium',text:'Which statement is used to bring in Python\'s built-in math module?',options:['include math','import math','using math','require math'],correct:1},
{id:'m3_10',module:'M3-R5',topic:'Data Structures',diff:'easy',text:'Which data structure does not allow duplicate values?',options:['List','Tuple','Set','Dictionary values'],correct:2},
{id:'m3_11',module:'M3-R5',topic:'Data Structures',diff:'medium',text:'Which data structure stores data in key-value pairs?',options:['List','Tuple','Dictionary','Set'],correct:2},
{id:'m3_12',module:'M3-R5',topic:'Data Structures',diff:'hard',text:'Which of these data types is immutable?',options:['List','Dictionary','Set','Tuple'],correct:3},
{id:'m3_13',module:'M3-R5',topic:'File Handling',diff:'medium',text:'Which mode opens a file for appending data in Python?',options:['"r"','"w"','"a"','"x"'],correct:2},
{id:'m3_14',module:'M3-R5',topic:'File Handling',diff:'medium',text:'Which block is used to handle exceptions in Python?',options:['try-except','if-else','for-in','def-return'],correct:0},
{id:'m3_15',module:'M3-R5',topic:'OOP',diff:'easy',text:'Which special method runs automatically when a Python object is created?',options:['__str__','__init__','__new__','__call__'],correct:1},
{id:'m3_16',module:'M3-R5',topic:'OOP',diff:'medium',text:'Which OOP concept allows a class to acquire properties of another class?',options:['Encapsulation','Inheritance','Polymorphism','Abstraction'],correct:1},

// ---------- M4-R5 ----------
{id:'m4_1',module:'M4-R5',topic:'Introduction to IoT',diff:'easy',text:'Which layer of IoT architecture collects data from the physical world?',options:['Application layer','Network layer','Perception layer','Middleware layer'],correct:2},
{id:'m4_2',module:'M4-R5',topic:'Introduction to IoT',diff:'medium',text:'What does "IoT" stand for?',options:['Internet of Technology','Internet of Things','Internal Object Transfer','Integration of Tools'],correct:1},
{id:'m4_3',module:'M4-R5',topic:'Introduction to IoT',diff:'medium',text:'Which of these is NOT a typical characteristic of IoT devices?',options:['Connectivity','Sensing','Manual-only operation','Data exchange'],correct:2},
{id:'m4_4',module:'M4-R5',topic:'Sensors & Actuators',diff:'easy',text:'Which of these is an actuator, not a sensor?',options:['Temperature sensor','Servo motor','PIR sensor','LDR'],correct:1},
{id:'m4_5',module:'M4-R5',topic:'Sensors & Actuators',diff:'medium',text:'Which low-cost microcontroller board is widely used in IoT prototyping?',options:['Arduino Uno','MS Word','LibreOffice Calc','Adobe Photoshop'],correct:0},
{id:'m4_6',module:'M4-R5',topic:'Sensors & Actuators',diff:'medium',text:'An LDR sensor is primarily used to detect:',options:['Temperature','Light intensity','Humidity','Sound'],correct:1},
{id:'m4_7',module:'M4-R5',topic:'Communication Protocols',diff:'easy',text:'Which lightweight protocol is commonly used for IoT messaging?',options:['FTP','MQTT','SMTP','SNMP'],correct:1},
{id:'m4_8',module:'M4-R5',topic:'Communication Protocols',diff:'medium',text:'Which short-range wireless technology is commonly used to connect IoT devices like earphones?',options:['Bluetooth','Ethernet','Fiber Optic','Coaxial Cable'],correct:0},
{id:'m4_9',module:'M4-R5',topic:'Communication Protocols',diff:'hard',text:'MQTT works on which basic messaging model?',options:['Client-Server only','Publish-Subscribe','Peer-to-Peer only','Broadcast only'],correct:1},
{id:'m4_10',module:'M4-R5',topic:'IoT Applications',diff:'easy',text:'Smart irrigation systems are an example of IoT in which domain?',options:['Smart agriculture','Industrial IoT','Smart home','Healthcare'],correct:0},
{id:'m4_11',module:'M4-R5',topic:'IoT Applications',diff:'medium',text:'A smart thermostat that learns your schedule is an example of IoT in:',options:['Smart home','Smart city traffic','Industrial IoT','Agriculture'],correct:0},
{id:'m4_12',module:'M4-R5',topic:'IoT Applications',diff:'medium',text:'Which of these is a major concern specific to IoT devices?',options:['Too many keyboard shortcuts','Security & privacy of connected devices','Lack of colour printers','Slow word processors'],correct:1},
];

/* ==================== QUICK NOTES (per topic) ==================== */
const NOTES = {
  'Introduction to Computers':'A computer works on the Input-Process-Output cycle. It stores data internally in binary (0s and 1s). Memory is of two types: Primary (RAM, Cache — volatile) and Secondary (Hard Disk, SSD, Pen Drive — non-volatile).',
  'Operating System Basics':'An OS manages hardware and software resources and acts as an interface between user and hardware. Examples: Windows, Linux, macOS. Key jobs: process management, memory management, file management, and providing a user interface.',
  'Word Processing':'Word processors (like LibreOffice Writer) are used to create, edit and format text documents. Key features: Mail Merge (personalized bulk letters), Track Changes (edit history), Tables, Styles, and Templates.',
  'Spreadsheets':'Spreadsheets (like LibreOffice Calc) organise data in rows and columns for calculation and analysis. Every formula starts with "=". Common functions: SUM, AVERAGE, COUNT, COUNTIF, IF. Charts help visualise data trends.',
  'Presentations':'Presentation software (like LibreOffice Impress) is used to create slide decks. Slide Master controls consistent design across all slides. Slide Sorter view helps rearrange slide order quickly.',
  'Networking Concepts':'A network connects computers to share data/resources. Topologies: Bus, Star, Ring, Mesh. LAN = small area (building), MAN = city-wide, WAN = large area (countries). Cyber security basics: strong passwords, avoid public WiFi for banking, keep software updated.',
  'HTML5 Fundamentals':'HTML defines the structure of a webpage using tags/elements. Semantic tags like <header>, <nav>, <section>, <footer> describe the meaning of content, improving accessibility and SEO.',
  'CSS3 Styling':'CSS controls the visual presentation of HTML. The Box Model (content → padding → border → margin) defines spacing. Flexbox and Grid are modern layout systems for building responsive designs.',
  'JavaScript Basics':'JavaScript adds interactivity to webpages. Variables: let/const (block-scoped) preferred over var. Functions group reusable code. The DOM (Document Object Model) lets JS read/modify page content dynamically.',
  'Website Publishing':'Publishing a website needs a Domain (address, e.g. example.com) and Hosting (server space). Files are typically uploaded via FTP. SEO improves visibility in search engine results.',
  'Python Basics':'Python is a high-level, easy-to-read programming language. Core data types: int, float, str, bool. print() displays output, input() takes user input.',
  'Control Structures':'if-elif-else handles decision making. for loops iterate over sequences; while loops repeat while a condition is true. break exits a loop, continue skips to the next iteration.',
  'Functions & Modules':'Functions (defined with def) let you reuse blocks of code. Modules (imported with import) provide pre-built functionality, e.g. the math module for mathematical operations.',
  'Data Structures':'List: ordered, mutable, allows duplicates [ ]. Tuple: ordered, immutable ( ). Dictionary: key-value pairs { }. Set: unordered, no duplicates { } — great for membership tests.',
  'File Handling':'Files are opened using open(filename, mode): "r" read, "w" write (overwrites), "a" append, "x" create. Always use try-except to handle errors like FileNotFoundError gracefully.',
  'OOP':'Class = blueprint, Object = instance. __init__ is the constructor, runs automatically on object creation. Inheritance lets a class reuse another class\'s properties/methods. Encapsulation hides internal details.',
  'Introduction to IoT':'IoT connects physical devices to the internet so they can sense, communicate and act. Basic architecture layers: Perception (sensing) → Network (communication) → Application (user-facing services).',
  'Sensors & Actuators':'Sensors sense the environment (temperature, light, motion) and convert it to electrical signals. Actuators act on the environment (motors, relays, buzzers). Arduino and Raspberry Pi are common IoT prototyping boards.',
  'Communication Protocols':'MQTT (lightweight, publish-subscribe) is popular for constrained IoT devices. Other protocols: HTTP (web), Bluetooth/WiFi (short range), Zigbee (low-power mesh networks).',
  'IoT Applications':'Real-world IoT: Smart Home (thermostats, lights), Smart Agriculture (soil moisture sensors, automated irrigation), Industrial IoT (equipment monitoring), Smart City (traffic, waste management). Security & privacy are major concerns as more devices connect.',
};

/* ==================== FLASHCARDS ==================== */
const FLASHCARDS = [
  {module:'M1-R5', front:'RAM', back:'Random Access Memory — volatile primary memory that temporarily stores data/instructions the CPU is currently using.'},
  {module:'M1-R5', front:'Star Topology', back:'A network layout where all devices connect to one central hub/switch.'},
  {module:'M1-R5', front:'Mail Merge', back:'A feature that combines a template document with a data source to create personalized copies (e.g. letters with different names).'},
  {module:'M1-R5', front:'Cyber Security', back:'Practices and technologies that protect systems, networks and data from digital attacks.'},
  {module:'M1-R5', front:'LAN', back:'Local Area Network — a network confined to a small area like one building or campus.'},
  {module:'M2-R5', front:'Semantic HTML', back:'Using HTML tags (like <nav>, <article>) that clearly describe their meaning/purpose, improving accessibility & SEO.'},
  {module:'M2-R5', front:'Box Model', back:'The CSS model describing an element as: content → padding → border → margin, from inside out.'},
  {module:'M2-R5', front:'DOM', back:'Document Object Model — a programming interface representing the HTML page as a tree of objects JS can manipulate.'},
  {module:'M2-R5', front:'Flexbox', back:'A CSS layout system for arranging items in a row or column with flexible sizing and alignment.'},
  {module:'M3-R5', front:'List vs Tuple', back:'List is mutable (can change) []; Tuple is immutable (cannot change) ().'},
  {module:'M3-R5', front:'__init__', back:'The constructor method in Python — runs automatically when a new object of a class is created.'},
  {module:'M3-R5', front:'Exception Handling', back:'Using try-except blocks to catch and handle runtime errors gracefully instead of crashing the program.'},
  {module:'M3-R5', front:'Dictionary', back:'A Python data structure storing data as key-value pairs, e.g. {"name": "Shivam"}.'},
  {module:'M4-R5', front:'MQTT', back:'Message Queuing Telemetry Transport — a lightweight publish-subscribe protocol ideal for constrained IoT devices.'},
  {module:'M4-R5', front:'Perception Layer', back:'The IoT architecture layer responsible for sensing data from the physical environment via sensors.'},
  {module:'M4-R5', front:'Actuator', back:'A device that acts on the environment based on signals (e.g. a motor, relay, or buzzer) — opposite of a sensor.'},
];

/* ==================== ACHIEVEMENTS ==================== */
const ACHIEVEMENTS = [
  {id:'first_quiz', title:'First Step', desc:'Complete your first quiz', icon:'🎯', check:(s)=> s.attempts.length>=1},
  {id:'streak_3', title:'On a Roll', desc:'3-day study streak', icon:'🔥', check:(s)=> s.streak>=3},
  {id:'streak_7', title:'Week Warrior', desc:'7-day study streak', icon:'⚡', check:(s)=> s.streak>=7},
  {id:'perfect', title:'Perfectionist', desc:'Score 100% in any quiz', icon:'💯', check:(s)=> s.attempts.some(a=>a.correct===a.total)},
  {id:'all_modules', title:'All Rounder', desc:'Attempt a quiz in every module', icon:'🏆', check:(s)=> SYLLABUS.every(m=>s.attempts.some(a=>a.moduleCode===m.code))},
  {id:'xp_500', title:'Rising Star', desc:'Earn 500 total XP', icon:'⭐', check:(s)=> Object.values(s.moduleXp).reduce((a,b)=>a+b,0)>=500},
  {id:'quiz_10', title:'Dedicated Learner', desc:'Complete 10 quizzes', icon:'📚', check:(s)=> s.attempts.length>=10},
  {id:'flashcard_fan', title:'Flashcard Fan', desc:'Review 20 flashcards', icon:'🗂️', check:(s)=> (s.flashcardsReviewed||0)>=20},
];
